#include "ioconf.h"

#include <stddef.h>

#define PV_REST_URL "http://10.0.3.10/solar_api/v1/GetPowerFlowRealtimeData.fcgi"

const IOCONF_CHAN_T ioconf_tab[] = {
  // PDOs from UVR
  { .topic = "uvr/temp/store/upper", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x201, .pos = 0, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
//  { .topic = "uvr/temp/store/lower", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
//    .can = { .can_id = 0x201, .pos = 2, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/temp/radi/send", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x201, .pos = 4, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/temp/radi/return", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x201, .pos = 6, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/temp/outdoor", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x281, .pos = 0, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/temp/garret", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x281, .pos = 2, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/temp/warm_water", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x281, .pos = 4, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/temp/circ_ret", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x281, .pos = 6, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/power/radi", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x301, .pos = 0, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/energ/radi", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x301, .pos = 2, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/temp/radi/sp", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x301, .pos = 4, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/flow/radi", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x301, .pos = 6, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = (1.0 / 60.0), .input = true } },
  { .topic = "uvr/power/hp", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x381, .pos = 0, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/energ/hp", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x381, .pos = 2, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/temp/hp/sp", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .can = { .can_id = 0x381, .pos = 4, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = true },
//    .mb = { .slave = 11, .addr = 1, .input_reg = false, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = false } },
    .mb = { .slave = 11, .addr = 10, .input_reg = false, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = false } },
  { .topic = "uvr/mixer/radi", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .can = { .can_id = 0x381, .pos = 6, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.0, .input = true } },

  { .topic = "uvr/hp_on", .type = IOCONF_CHAN_TYPE_SWITCH,
    .can = { .can_id = 0x181, .pos = 0, .type = IOCONF_CAN_TYPE_BIT, .input = true },
//    .mb = { .slave = 11, .addr = 4, .input_reg = false, .type = IOCONF_MB_TYPE_UNSIGNED, .offset = 0.0, .scale = 1.0, .input = false } },
    .mb = { .slave = 11, .addr = 12, .input_reg = false, .type = IOCONF_MB_TYPE_UNSIGNED, .offset = 0.0, .scale = 1.0, .input = false } },
  { .topic = "uvr/gen_on", .type = IOCONF_CHAN_TYPE_SWITCH,
    .can = { .can_id = 0x181, .pos = 1, .type = IOCONF_CAN_TYPE_BIT, .input = true } },
  { .topic = "uvr/pump/radi", .type = IOCONF_CHAN_TYPE_SWITCH,
    .can = { .can_id = 0x181, .pos = 2, .type = IOCONF_CAN_TYPE_BIT, .input = true } },
  { .topic = "uvr/pump/circ", .type = IOCONF_CHAN_TYPE_SWITCH,
    .can = { .can_id = 0x181, .pos = 3, .type = IOCONF_CAN_TYPE_BIT, .input = true } },

  // PDOs from FOGO
  { .topic = "uvr/fogo/rpm", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1000, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/load_p", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .mb = { .slave = 10, .addr = 1016, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/fogo/load_q", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .mb = { .slave = 10, .addr = 1020, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/fogo/load_s", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .mb = { .slave = 10, .addr = 1024, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/fogo/pwrfact", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
    .mb = { .slave = 10, .addr = 1028, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.01, .input = true } },
  { .topic = "uvr/fogo/freq", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .mb = { .slave = 10, .addr = 1032, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.1, .input = true } },

  { .topic = "uvr/fogo/volt_l1-n", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1033, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/volt_l2-n", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1034, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/volt_l3-n", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1035, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/volt_l1-l1", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1036, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/volt_l2-l2", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1037, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/volt_l3-l1", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1038, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/curr_l1", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1039, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/curr_l2", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1040, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/curr_l3", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1041, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },

  { .topic = "uvr/fogo/volt_bat", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .mb = { .slave = 10, .addr = 1051, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.1, .input = true } },
  { .topic = "uvr/fogo/volt_alt", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .mb = { .slave = 10, .addr = 1052, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.1, .input = true } },

  { .topic = "uvr/fogo/temp_coolant", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1053, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/temp_canopy", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1054, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/level_fuel", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1055, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/temp_exhaust", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 1056, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },

  { .topic = "uvr/fogo/emerg_stop", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1058, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },
  { .topic = "uvr/fogo/cnt_alarms", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .mb = { .slave = 10, .addr = 4214, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 1.0, .input = true } },

  { .topic = "uvr/fogo/din/remote_start", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1057, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 0.0, .input = true } },
  { .topic = "uvr/fogo/din/emerg_stop", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1057, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 1.0, .input = true } },
  { .topic = "uvr/fogo/din/mcb_on", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1057, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 2.0, .input = true } },
  { .topic = "uvr/fogo/din/gcb_on", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1057, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 3.0, .input = true } },
  { .topic = "uvr/fogo/din/coolant_overtemp", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1057, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 5.0, .input = true } },
  { .topic = "uvr/fogo/din/oil_press_fault", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1057, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 6.0, .input = true } },
  { .topic = "uvr/fogo/din/charger_ok", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1057, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 7.0, .input = true } },

  { .topic = "uvr/fogo/dout/fuel_solenoid", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1059, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 0.0, .input = true } },
  { .topic = "uvr/fogo/dout/starter", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1059, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 1.0, .input = true } },
  { .topic = "uvr/fogo/dout/preheat", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1059, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 2.0, .input = true } },
  { .topic = "uvr/fogo/dout/horn", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1059, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 3.0, .input = true } },
  { .topic = "uvr/fogo/dout/gcb_off_coil", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1059, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 4.0, .input = true } },
  { .topic = "uvr/fogo/dout/coolant_pump", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1059, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 5.0, .input = true } },
  { .topic = "uvr/fogo/dout/canopy_fan", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1059, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 6.0, .input = true } },
  { .topic = "uvr/fogo/dout/gcb_close", .type = IOCONF_CHAN_TYPE_SWITCH,
    .mb = { .slave = 10, .addr = 1059, .input_reg = true, .type = IOCONF_MB_TYPE_BITMASK, .offset = 7.0, .input = true } },

  // PDOs from DAIKIN
  { .topic = "uvr/daikin/temp_heat_exchanger", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
    .mb = { .slave = 11, .addr = 40, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.01, .input = true },
    .can = { .can_id = 0x202, .pos = 0, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = false, .send = false } },
  { .topic = "uvr/daikin/temp_backup_heater", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
    .mb = { .slave = 11, .addr = 41, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.01, .input = true } },
  { .topic = "uvr/daikin/temp_return", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
    .mb = { .slave = 11, .addr = 42, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.01, .input = true },
    .can = { .can_id = 0x202, .pos = 2, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = false, .send = false } },
//  { .topic = "uvr/daikin/temp_warm_water", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
  { .topic = "uvr/temp/store/lower", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
    .mb = { .slave = 11, .addr = 43, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.01, .input = true },
    .can = { .can_id = 0x202, .pos = 6, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = false, .send = false } },
  { .topic = "uvr/daikin/temp_outdoor", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
    .mb = { .slave = 11, .addr = 44, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.01, .input = true } },
  { .topic = "uvr/daikin/temp_refrigerant", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
    .mb = { .slave = 11, .addr = 45, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.01, .input = true } },
  { .topic = "uvr/daikin/flow", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.2f",
    .mb = { .slave = 11, .addr = 49, .input_reg = true, .type = IOCONF_MB_TYPE_SIGNED, .offset = 0.0, .scale = 0.01, .input = true },
    .can = { .can_id = 0x202, .pos = 4, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = (1.0 / 60.0), .input = false, .send = true } },

  // PDOs from Fronius GEN24
  { .topic = "uvr/pv/soc", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .rest = { .url = PV_REST_URL, .path = "Body.Data.Inverters.1.SOC", .offset = 0.0, .scale = 1.0 },
    .can = { .can_id = 0x302, .pos = 0, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 0.1, .input = false, .send = true } },
  { .topic = "uvr/pv/power_bat", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.1f",
    .rest = { .url = PV_REST_URL, .path = "Body.Data.Site.P_Akku", .offset = 0.0, .scale = 1.0 },
    .can = { .can_id = 0x282, .pos = 0, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 1.0, .input = false, .send = false } },
  { .topic = "uvr/pv/power_grid", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .rest = { .url = PV_REST_URL, .path = "Body.Data.Site.P_Grid", .offset = 0.0, .scale = 1.0 },
    .can = { .can_id = 0x282, .pos = 2, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 1.0, .input = false, .send = false } },
  { .topic = "uvr/pv/power_load", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .rest = { .url = PV_REST_URL, .path = "Body.Data.Site.P_Load", .offset = 0.0, .scale = 1.0 },
    .can = { .can_id = 0x282, .pos = 4, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 1.0, .input = false, .send = false } },
  { .topic = "uvr/pv/power_pv", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f",
    .rest = { .url = PV_REST_URL, .path = "Body.Data.Site.P_PV", .offset = 0.0, .scale = 1.0 },
    .can = { .can_id = 0x282, .pos = 6, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 1.0, .input = false, .send = true } },

  // PDOs from OpenHAB
//  { .topic = "uvr/pv_surplus", .type = IOCONF_CHAN_TYPE_NUMBER, .fmt = "%.0f", .subscribe = true,
//    .can = { .can_id = 0x282, .pos = 0, .type = IOCONF_CAN_TYPE_S16, .offset = 0.0, .scale = 1.0, .input = false, .send = true } },

  { .topic = NULL }
};

